# -*- coding: utf-8 -*-
"""breastcancer_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxsES4adyzw5XSIDJTXCOZ5a7jdYrdc4
"""

import pandas as pd

data = pd.read_csv('/content/breastcancer_data.csv')

data.head()

from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

result = label.fit_transform(data.diagnosis)

data.head()

data['result']=result

X = data.drop(['diagnosis','Unnamed: 32'],axis=1)
Y = data['result']

from sklearn.model_selection import train_test_split

X_train , X_test , Y_train , Y_test = train_test_split(X ,Y, test_size=0.2, stratify=Y, random_state=3)

from sklearn.linear_model import LogisticRegression

Lmodel = LogisticRegression()

Lmodel.fit(X_train,Y_train)

from sklearn import svm

Smodel = svm.SVC()

Smodel.fit(X_train,Y_train)

from sklearn.metrics import accuracy_score

Lpred = Lmodel.predict(X_train)
Laccuracy = accuracy_score(Lpred,Y_train)

Spred = Smodel.predict(X_train)
Saccuracy = accuracy_score(Spred, Y_train)

print(Laccuracy )
print(Saccuracy)

